blank_issues_enabled: true
contact_links:
  - name: Add new ToDo
    about: made by config.yml
    # edit {username} and {repo} for your environment
    url: https://github.com/sigibeem/ToDo/issues/new?template=custom.md&projects=sigibeem%2FToDo%2F1&labels=ToDo
